### ISSUE TITLE
My referrals page of ID 70000 is showing ID 70002 as his referral. But 700002 belongs to ID 700001

### ISSUE THREAD

**Issue by hustynetwork** [hustynetwork/Nuvizion#17]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52190386/194812209-c8e3d99e-1dd4-4d79-8e87-2e3d7f50ec53.png">

**Comment by akram37460** [comment]
Sir, I've Removed "Unlimited Unilevel" because My referrals and Unlimited Unilevel showing the same recode

**Comment by hustynetwork** [comment]
70002's sponsor is 70001. 
Why is 70002 is in 70000's my referrals list?

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/52190386/194933688-8f7e01b4-2e92-4ef2-ba6f-7c867a376100.png">
