### ISSUE TITLE
70000 referred 700001 and got $20 but didn't get $5 (Since there is no one above user 70000, 70000 should get the $5 too).

### ISSUE THREAD

**Issue by hustynetwork** [hustynetwork/Nuvizion#7]

**Comment by hustynetwork** [comment]
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/52190386/194812444-228ebd39-e1b0-46cd-b2db-497b6697ad0b.png">

$5 from ID 70001 is not received to 70000

**Comment by akram37460** [comment]
Done
