### ISSUE TITLE
Income history -> Auto pool income history not working. Earning shows 0 after 700001 bought plan 2.

### ISSUE THREAD

**Issue by hustynetwork** [hustynetwork/Nuvizion#8]
<img width="833" alt="image" src="https://user-images.githubusercontent.com/52190386/194263240-17f57391-db2f-41ed-b1d4-58bb53c4f919.png">

2 users joined below ID 70000 but only 1 auto pool income is showing.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/52190386/194263648-d845616b-3997-4a4a-9e65-a12baf0468c4.png">
Another is showing in this tab.

Looks something wrong.

**Comment by akram37460** [comment]
Done
